### ISSUE TITLE
Fatal Error updating with Composer

### ISSUE THREAD

**Issue by GhostInTheMachines** [AcroMedia/commerce-install#13]
Ran composer update today and received the following error.

  [RuntimeException]                                                                                                 
  Could not scan for classes inside "docroot/modules/contrib/lightning_core/tests/contexts/AwaitTrait.inc" which do  
  es not appear to be a file nor a folder

A Google search didn't turn up any related issues but the site appears to still be up and running.

Any ideas how to troubleshoot this a little further?

**Comment by smmccabe** [comment]
Likely an issue with Lightning and not with commerce install, once you've done the initial install, you're pretty much done with anything custom from us. I would recommend confirming your composer version is the most up to date on though, as old composer versions can give issues like this.

**Comment by GhostInTheMachines** [comment]
I nuked the directory and started over.  Kind of a Hail Mary but it is not throwing the error anymore.
