### ISSUE TITLE
GPL-2.0+ is deprecated, use GPL-2-or-later

### ISSUE THREAD

**Issue by mglaman** [AcroMedia/commerce-install#3]
See https://github.com/composer/packagist/issues/858

I don't know if this is here or https://github.com/smmccabe/accompanist. Honestly it may be both, as https://github.com/smmccabe/accompanist should not supported that license anymore and consider it invalid.

**Comment by smmccabe** [comment]
it is actually coming from here, which is what we use as our base. https://github.com/drupalcommerce/project-base 

I did correct it in our version for now though. Accompanist is GPL3 and not causing issue.

https://github.com/AcroMedia/commerce-install-backend/commit/07b266c6f69bac82e6a2c510de8036b87c022914

**Comment by mglaman** [comment]
Ah, thanks! I can update project-base
