### ISSUE TITLE
I believe this should be Drupal Commerce 1.x . . .

### ISSUE THREAD

**Issue by frederickjh** [AcroMedia/commerce-install#5]
. . . or is Drupal Commerce 2.x also available for Drupal 7?

https://github.com/AcroMedia/commerce-install/blob/fa57731078c09313b51940280539caa2250025e1/src/components/Kickstart.vue#L38-L42

**Comment by joshmiller83** [comment]
This is a common question. Commerce Kickstart has two distribution versions, both for Drupal 7:

1. 7.x-1.x - Separately maintained, minimalist approach, only requires the most basic modules to make Drupal Commerce run a "normal" setup.
2. 7.x-2.x - Everything and the kitchen sink.

For Drupal 8, the website is the distribution, helping you build out your own composer.json file.

**Comment by frederickjh** [comment]
Yes but the link goes to the demo of the Drupal 7 Commerce Kickstart 1.0 not to a Commerce Kickstart 2.0 Demo. Wappalyzer agrees that it is Drupal 7.
![image](https://user-images.githubusercontent.com/864159/37527568-9d55f4aa-2932-11e8-8541-f377914ade3d.png)

**Comment by thejacer87** [comment]
@frederickjh **Commerce Kickstart 2.x** is not the same as *Drupal Commerce 2.x Installer*

Kickstart 2.x is a druphttps://github.com/AcroMedia/commerce-install/issues/6al7 install profile (right @joshmiller83?)

Commerce 2.x is Drupal 8 **ONLY** 
This website is a "kickstarter" for commerce 2.x, which generates a composer.json 

this: ![image](https://user-images.githubusercontent.com/6412919/37546714-5acdfc2e-292b-11e8-9700-8b9c5c58541f.png)
 is a link to the old kickstart 2.x demo site

with the drupal 8 move to composer, kickstart had a philosophy change too. 

checkout [ryan's blog](https://commerceguys.com/blog/whats-plan-commerce-kickstart-drupal-8) for more of an explanation

**Comment by frederickjh** [comment]
@thejacer87  and @joshmiller83 Thanks for the clarifications, sorry to leave my question about my confusion so long in the issue queue. I think I missed the other emails in my inbox.
