### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by JerzyR** [AcroMedia/commerce-install#6]
who had an idea to put installation into a 'web' folder instead of normally root folder of a web site?
how to move it now to root dir
And of course it ended with errors, the site looks like without any theme at all

**Comment by joshmiller83** [comment]
It's best practice to place your files up a level. Drupal community has generally settled on "web" but you can call it whatever you like. Composer does need a non-webroot accessible folder to store the vendor directory which is why this is happening.
